version: '3'

services:
  nginx:
    image: nginx:1.12-alpine
    links:
      - javadocky
    ports:
      - '80:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
  javadocky:
    build: .
    expose:
      - '8080'
