name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/checkout@v1
    - name: Build with Yarn
      run: |
        yarn install
        yarn build
