name: Build
on:
  push:
    branches: master
  pull_request_target:
    branches: master

# set necessary permissions for SQ's GitHub integration
# https://docs.sonarqube.org/latest/analysis/github-integration/#header-2
permissions:
  checks: write
  contents: read
  pull-requests: write
  statuses: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Decide the ref to check out
      uses: haya14busa/action-cond@v1
      id: condval
      with:
        cond: ${{ github.event_name == 'pull_request_target' }}
        if_true: refs/pull/${{ github.event.pull_request.number }}/merge
        if_false: ${{ github.ref }}
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ steps.condval.outputs.value }}
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: temurin
    - run: >
        ./gradlew spotlessCheck build sonarqube
        -x integrationTest --no-daemon --scan
        -Dsonar.organization=kengotoda-github
        -Dsonar.projectKey=javadocky
        -Dsonar.host.url=https://sonarcloud.io
        ${PR_NUMBER:+ -Dsonar.pullrequest.key=$PR_NUMBER -Dsonar.pullrequest.branch=${PR_BRANCH} }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_BRANCH: ${{ github.event.pull_request.head.ref }}
    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: build reports
        path: build/reports
  integrationTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: temurin
        cache: gradle
    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'
    - name: Install google-chrome-stable
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install google-chrome-stable
    - name: Run Integration Test
      run: npx percy exec -- ./gradlew integrationTest
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test results
        path: build/test-results/integrationTest
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Image
      run: |
        docker build -t kengotoda/javadocky .
