name: Build
on:
  push:
    branches: master
  pull_request_target:
    branches: master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: 15
        distribution: adopt
    - name: Build with Gradle
      uses: paambaati/codeclimate-action@v2.7.5
      with:
        coverageCommand: ./gradlew spotlessCheck build sonarqube -x integrationTest -Dsonar.organization=kengotoda-github -Dsonar.projectKey=javadocky -Dsonar.host.url=https://sonarcloud.io
        coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java ${{github.workspace}}/src/main/kotlin"
    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: build reports
        path: build/reports
  integrationTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: 15
        distribution: adopt
    - name: Set up NodeJS 12
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: Install google-chrome-stable
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install google-chrome-stable
    - name: Run Integration Test
      run: npx percy exec -- ./gradlew integrationTest
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test results
        path: build/test-results/integrationTest
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Image
      run: |
        docker build -t kengotoda/javadocky .
