name: Build
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v7.0.1
      with:
        fetch-depth: 0
    - uses: gradle/actions/wrapper-validation@v6
    - name: Set up JDK 17
      uses: actions/setup-java@v5.7.0
      with:
        java-version: 17
        distribution: temurin
        cache: gradle
    - run: >
        ./gradlew spotlessCheck build -x integrationTest --no-daemon
    - name: Upload Test Report
      uses: actions/upload-artifact@v7.0.1
      if: always()
      with:
        name: build reports
        path: build/reports
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - run: docker build .
  integrationTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.1
    - name: Set up JDK 17
      uses: actions/setup-java@v5.7.0
      with:
        java-version: 17
        distribution: temurin
        cache: gradle
    - name: Set up Node.js
      uses: actions/setup-node@v7.0.0
      with:
        node-version-file: '.nvmrc'
    - name: Install Google Chrome
      uses: browser-actions/setup-chrome@v1
      id: setup-chrome
      with:
        install-chromedriver: true
    - name: Run Integration Test
      run: npx @percy/cli exec -- ./gradlew integrationTest --no-build-cache
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        JAVA_TOOL_OPTIONS: -Dwebdriver.chrome.driver=${{ steps.setup-chrome.outputs.chromedriver-path }}
    - name: Upload Test Report
      uses: actions/upload-artifact@v7.0.1
      if: failure()
      with:
        name: integration test reports
        path: build/reports
