name: Pull Request
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  cache:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/checkout@v1
      - name: Build with Gradle
        run: ./gradlew assemble
      - uses: ./.github/actions/gradle-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: 'cache'
      - name: check cache result
        run: |
          ls /opt/hostedtoolcache/gradle/caches/1.0.0/x64
          ls $HOME/.gradle/caches
